// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class StoryTextManager : MonoBehaviour {
	public TextAsset storyFile;
	void Start(){
		Load (storyFile);
	}
	public class Row
	{
		public string SCENENAME;
		public string SPEAKER_ORDER;
		public string SPEAKER_1;
		public string TEXT_1;
		public string SPEAKER_2;
		public string TEXT_2;
		public string SPEAKER_3;
		public string TEXT_3;
		public string SPEAKER_4;
		public string TEXT_4;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.SCENENAME = grid[i][0];
			row.SPEAKER_ORDER = grid[i][1];
			row.SPEAKER_1 = grid[i][2];
			row.TEXT_1 = grid[i][3];
			row.SPEAKER_2 = grid[i][4];
			row.TEXT_2 = grid[i][5];
			row.SPEAKER_3 = grid[i][6];
			row.TEXT_3 = grid[i][7];
			row.SPEAKER_4 = grid[i][8];
			row.TEXT_4 = grid[i][9];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_SCENENAME(string find)
	{
		return rowList.Find(x => x.SCENENAME == find);
	}
	public List<Row> FindAll_SCENENAME(string find)
	{
		return rowList.FindAll(x => x.SCENENAME == find);
	}
	public Row Find_SPEAKER_ORDER(string find)
	{
		return rowList.Find(x => x.SPEAKER_ORDER == find);
	}
	public List<Row> FindAll_SPEAKER_ORDER(string find)
	{
		return rowList.FindAll(x => x.SPEAKER_ORDER == find);
	}
	public Row Find_SPEAKER_1(string find)
	{
		return rowList.Find(x => x.SPEAKER_1 == find);
	}
	public List<Row> FindAll_SPEAKER_1(string find)
	{
		return rowList.FindAll(x => x.SPEAKER_1 == find);
	}
	public Row Find_TEXT_1(string find)
	{
		return rowList.Find(x => x.TEXT_1 == find);
	}
	public List<Row> FindAll_TEXT_1(string find)
	{
		return rowList.FindAll(x => x.TEXT_1 == find);
	}
	public Row Find_SPEAKER_2(string find)
	{
		return rowList.Find(x => x.SPEAKER_2 == find);
	}
	public List<Row> FindAll_SPEAKER_2(string find)
	{
		return rowList.FindAll(x => x.SPEAKER_2 == find);
	}
	public Row Find_TEXT_2(string find)
	{
		return rowList.Find(x => x.TEXT_2 == find);
	}
	public List<Row> FindAll_TEXT_2(string find)
	{
		return rowList.FindAll(x => x.TEXT_2 == find);
	}
	public Row Find_SPEAKER_3(string find)
	{
		return rowList.Find(x => x.SPEAKER_3 == find);
	}
	public List<Row> FindAll_SPEAKER_3(string find)
	{
		return rowList.FindAll(x => x.SPEAKER_3 == find);
	}
	public Row Find_TEXT_3(string find)
	{
		return rowList.Find(x => x.TEXT_3 == find);
	}
	public List<Row> FindAll_TEXT_3(string find)
	{
		return rowList.FindAll(x => x.TEXT_3 == find);
	}
	public Row Find_SPEAKER_4(string find)
	{
		return rowList.Find(x => x.SPEAKER_4 == find);
	}
	public List<Row> FindAll_SPEAKER_4(string find)
	{
		return rowList.FindAll(x => x.SPEAKER_4 == find);
	}
	public Row Find_TEXT_4(string find)
	{
		return rowList.Find(x => x.TEXT_4 == find);
	}
	public List<Row> FindAll_TEXT_4(string find)
	{
		return rowList.FindAll(x => x.TEXT_4 == find);
	}

}